server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
okta:
  oauth2:
    issuer: https://dev-60363091.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
      
      
